SELECT * FROM STOCK_DATA;

#1. 현재가가 높은 순서대로 RANK()써서 랭킹 표시하면서 리스트업하기
SELECT STOCK_NAME, CURRENT_PRICE, RANK() OVER(ORDER BY CURRENT_PRICE DESC) AS '랭킹' 
FROM STOCK_DATA ORDER BY CURRENT_PRICE DESC;

#2. 거래량(trading_volume)이 50만 이하면 매우 적음, 100만 이하면 적음, 500만 이하면 보통, 1000만 이하면 많음, 그외 매우 많음 한다음에 매우많은것부터 나열
SELECT * FROM STOCK_DATA;

SELECT 
    STOCK_NAME, TRADING_VOLUME, 
    CASE
        WHEN TRADING_VOLUME <= 500000 THEN '매우낮음'
        WHEN TRADING_VOLUME <= 1000000 THEN '낮음' 
        WHEN TRADING_VOLUME <= 5000000 THEN '보통' 
        WHEN TRADING_VOLUME <= 10000000 THEN '많음' 
        ELSE '매우 많음' 
    END AS '거래량평가'
FROM STOCK_DATA;

#3. 시가와 비교하여 고가의 비율 증가이 높은 순서대로 랭킹 표시해서 나열
SELECT STOCK_NAME, OPENING_PRICE, CURRENT_PRICE, (CURRENT_PRICE/OPENING_PRICE) AS '증가비율', RANK() OVER(ORDER BY (CURRENT_PRICE/OPENING_PRICE) DESC) AS '랭킹' 
FROM STOCK_DATA ORDER BY (CURRENT_PRICE/OPENING_PRICE) DESC;

#4. 현재가(3:30기준)와 시가의 차이를 계산해서 100주씩(opening_price - current_price)*100 가지고 있다는 가정하에 벌어드린 수익 나열
SELECT STOCK_NAME, OPENING_PRICE, CURRENT_PRICE, (OPENING_PRICE - CURRENT_PRICE)*100 AS '수익', RANK() OVER(ORDER BY (OPENING_PRICE - CURRENT_PRICE)*100 DESC) AS '랭킹' 
FROM STOCK_DATA ORDER BY (OPENING_PRICE - CURRENT_PRICE) DESC;

#5. 고가 - 저가 순위 매기기(high_price - low_price)
SELECT STOCK_NAME, HIGH_PRICE, LOW_PRICE, (HIGH_PRICE - LOW_PRICE) AS '차액', RANK() OVER(ORDER BY (HIGH_PRICE - LOW_PRICE) DESC) AS '랭킹' 
FROM STOCK_DATA ORDER BY (HIGH_PRICE - LOW_PRICE) DESC;