server {
    listen 80;

    location / {
        proxy_pass http://streamlit_app:8501; # 서비스 이름은 유지하되 포트만 8501로 변경
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
